# Generated by Django 4.1.2 on 2023-03-10 08:39

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_title', models.CharField(max_length=155)),
                ('description', mdeditor.fields.MDTextField(default='')),
                ('solution_slug', models.SlugField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'solution',
            },
        ),
    ]
