# Generated by Django 4.1.2 on 2023-03-30 07:17

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(max_length=255)),
                ('region_type', models.CharField(max_length=255)),
                ('solution_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'CategoryPartner',
                'verbose_name_plural': 'CategoryPartners',
            },
        ),
        migrations.CreateModel(
            name='ContentPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='image')),
                ('desc', mdeditor.fields.MDTextField()),
                ('categoryPartner_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('contentPartner_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('categoryPartner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='partnership.categorypartner')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.RemoveField(
            model_name='partner',
            name='relation',
        ),
        migrations.DeleteModel(
            name='Partnering',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
