# Generated by Django 4.1.2 on 2023-03-13 08:43

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features_title', models.CharField(max_length=255)),
                ('features_desc', mdeditor.fields.MDTextField()),
                ('feature_thumbnail', models.ImageField(upload_to='image')),
                ('category_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('features_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='featuress.category')),
            ],
        ),
        migrations.CreateModel(
            name='SubFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_features_title', models.CharField(max_length=255)),
                ('sub_features_desc', mdeditor.fields.MDTextField()),
                ('features_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('sub_features_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='featuress.features')),
            ],
        ),
        migrations.CreateModel(
            name='SubSubFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='image')),
                ('title', models.CharField(max_length=255)),
                ('desc', mdeditor.fields.MDTextField()),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='featuress.subfeatures')),
            ],
        ),
    ]
