# Generated by Django 4.1.2 on 2023-03-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featuress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='category_slug',
        ),
        migrations.RemoveField(
            model_name='features',
            name='feature_category',
        ),
        migrations.RemoveField(
            model_name='features',
            name='features_slug',
        ),
        migrations.RemoveField(
            model_name='subfeatures',
            name='features_slug',
        ),
        migrations.AddField(
            model_name='features',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='features',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subfeatures',
            name='features_titles',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subfeatures',
            name='fetures_slug',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='subsubfeatures',
            name='sub_features_titles',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subfeatures',
            name='sub_features_slug',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
