# Generated by Django 4.1.2 on 2023-03-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featuress', '0004_alter_benefitfeatures_options_alter_features_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitfeatures',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='features',
            name='feature_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
