# Generated by Django 4.1.2 on 2023-03-10 06:24

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=255)),
                ('thumbnail', models.URLField()),
                ('description', mdeditor.fields.MDTextField(default='')),
                ('features_slug', models.SlugField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'features',
            },
        ),
    ]
