# Generated by Django 4.1.2 on 2023-03-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='thumbnail',
            field=models.ImageField(upload_to='image'),
        ),
    ]
