# Generated by Django 4.1.2 on 2023-03-10 07:32

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_feature_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features_title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='image')),
                ('description', mdeditor.fields.MDTextField(default='')),
                ('content_tittle', models.CharField(max_length=255)),
                ('content_thumbnail', models.ImageField(upload_to='image')),
                ('content_description', mdeditor.fields.MDTextField(default='')),
                ('features_slug', models.SlugField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'features',
            },
        ),
        migrations.DeleteModel(
            name='feature',
        ),
    ]
