# Generated by Django 4.1.2 on 2023-03-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_features_delete_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='features_title',
            new_name='features_tittle',
        ),
    ]
